#!/bin/bash
#PBS -l walltime=18:00:00  
#PBS -l select=1:ncpus=128:mem=64gb
#PBS -N batch_sim_sigma1e-1
#PBS -o batch_sim_sigma1e-1.out
#PBS -e batch_sim_sigma1e-1.err
cd ${PBS_O_WORKDIR}

export PATH="$HOME/miniforge3/bin:$PATH"
source ~/miniforge3/bin/activate collusion

SIGMA_U_VAL=0.1
PREV_PATH="/rds/general/user/mc4724/home/data/sigma_u_0.1_part_0.pt"

echo "Starting Python simulation with:"
echo "Sigma_u: ${SIGMA_U_VAL}"

python simulate_batch.py \
    --sigma_u ${SIGMA_U_VAL} \
    --cont ${PREV_PATH}

echo "Python script finished."