#!/bin/bash
#PBS -l walltime=08:00:00  
#PBS -l select=1:ncpus=128:mem=32gb
#PBS -N conv_test1
#PBS -o conv_test1.out
#PBS -e conv_test1.err 

cd ${PBS_O_WORKDIR}

export PATH="$HOME/miniforge3/bin:$PATH"
source ~/miniforge3/bin/activate collusion


SIM_BATCH_SIZE=1000
SIM_STEPS=50000
SIM_CONV=1000

OUTPUT_FILE="/rds/general/user/mc4724/home/data/tests/batch_sigma-1_conv_1.pt"
SIGMA_U_VAL=0.1

echo "Starting Python simulation with:"
echo "Batch size: ${SIM_BATCH_SIZE}"
echo "Steps: ${SIM_STEPS}"
echo "Sigma_u: ${SIGMA_U_VAL}"
echo "Output file: ${OUTPUT_FILE}"
echo "Device: cpu"

python simulate_cpu.py \
    --batch ${SIM_BATCH_SIZE} \
    --steps ${SIM_STEPS} \
    --sigma_u ${SIGMA_U_VAL} \
    --device cpu \
    --out ${OUTPUT_FILE} \
    --convergence ${SIM_CONV}
echo "Python script finished."