#!/bin/bash
#PBS -l walltime=00:30:00  
#PBS -l select=1:ncpus=128:mem=16gb
#PBS -N save_load  
#PBS -o save_load.out
#PBS -e save_load.err 

cd ${PBS_O_WORKDIR}

export PATH="$HOME/miniforge3/bin:$PATH"
source ~/miniforge3/bin/activate collusion


SIM_BATCH_SIZE=1000 
SIM_STEPS=500

OUTPUT_FILE="/rds/general/user/mc4724/home/data/batch_sigma-1_b${SIM_BATCH_SIZE}.pt"
SIGMA_U_VAL=0.1

echo "Starting Python simulation with:"
echo "Batch size: ${SIM_BATCH_SIZE}"
echo "Steps: ${SIM_STEPS}"
echo "Workers: ${SIM_WORKERS}"
echo "Sigma_u: ${SIGMA_U_VAL}"
echo "Output file: ${OUTPUT_FILE}"
echo "Device: cpu"

python simulate_cpu.py \
    --batch ${SIM_BATCH_SIZE} \
    --steps ${SIM_STEPS} \
    --sigma_u ${SIGMA_U_VAL} \
    --device cpu \
    --out ${OUTPUT_FILE}
echo "Simulation Finished, saved"
python simulate_cpu.py \
    --batch ${SIM_BATCH_SIZE} \
    --steps ${SIM_STEPS} \
    --sigma_u ${SIGMA_U_VAL} \
    --device cpu \
    --load ${OUTPUT_FILE}\
    --out ${OUTPUT_FILE}

echo "Python script finished."