#!/bin/bash
#PBS -N mm_test_gpu
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=4:mem=24gb:ngpus=1:gpu_type=RTX6000
#PBS -j oe

cd ${PBS_O_WORKDIR}

# make conda & python visible
export PATH="$HOME/miniforge3/bin:$PATH"
source ~/miniforge3/bin/activate collusion

python simulate_gpu.py \
    --batch 16 \
    --steps 1000 \
    --out test_Qtable_gpu.pt

echo "GPU test run finished on $(hostname) at $(date)"
